name: Node CI

on:
  push:
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'markdown.css'
      - 'package*.json'
      - 'bun.lock'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node: [22, 24]
        os: ['ubuntu-latest', 'windows-latest', 'macOS-latest']

    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Use Node.js ${{ matrix.node }}.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node }}.x

      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      - name: install
        run: bun install

      - name: lint
        run: bunx xo
        if: matrix.os == 'ubuntu-latest'

      - name: build
        run: bun run build

      - name: test lib
        run: bunx nyc ava src/test/lib.spec.ts --timeout=1m

      - name: test api
        run: bunx ava src/test/api.spec.ts --timeout=1m

      - name: test cli
        run: bunx ava src/test/cli.spec.ts --timeout=2m
        if: matrix.os != 'windows-latest' # because they just time out ¯\_(ツ)_/¯
